### ISSUE TITLE
Verify the range of `n` parameter of getPrivateKey

### ISSUE THREAD

**Issue by arai-a** [franziskuskiefer/webcrypto-ec#2]
at least when `algorithm.NamedCurve` is "P-256", "P-384" or "P-521", the length of privateKey should be fixed, and `n` and the resulting private key value should fit into the length.

For tSOKE purpose, `n` should be same as "P-256" etc's generator's `n`, but it might not be necessary for this API layer.

**Comment by franziskuskiefer** [comment]
I think we can remove `n` as a parameter. The curve is given in the `algorithm` and the implementation has to be able to get the order of the curve generator.

**Comment by arai-a** [comment]
am I understand correctly that `n` depends on both the curve and generator point?
iiuc, we're going to use the same curve as `algorithm` and different generator point.
so it's not guaranteed that `n` is same as `algorithm`'s generator point.

of course, for our usage it's supposed to be same and we can specialize the API for this specific purpose tho.

**Comment by franziskuskiefer** [comment]
If the order of `G` and `G'` is different you created a sub-group, which could allow small sub-group attacks. So that's something you don't want. Regardless, `n` is the order of `G`. The `mod` operation here as part of the private key generation is only to make sure that the key has a valid value, i.e. is smaller than the order of the group. So it always has to happen and isn't specific to our use case.

**Comment by arai-a** [comment]
So, the spec requires the G parameter of `mul` method to have the same order as the specified algorithm's generator, right?

I'm not sure if it's feasible to *check* that the passed generator has the same order (and throw if not) as an API tho (actually I still haven't figured out how I can),
saying that "they're supposed to be same" in the spec sounds reasonable.

**Comment by franziskuskiefer** [comment]
> I'm not sure if it's feasible to check that the passed generator has the same order (and throw if not)

The API should probably do it to prevent people from messing up. The order of an element `G` is the smallest number `x` such that `xG=1`. So that's easy enough to check when we have the order of the group generator.

**Comment by arai-a** [comment]
Thanks!

Removed n parameter and added the verification step
https://github.com/franziskuskiefer/webcrypto-ec/commit/3b55a25724980857ef0e50d6426e1d0d7bf384ab
