### ISSUE TITLE
is EC private key alone representable in WebCrypto and NSS level ?

### ISSUE THREAD

**Issue by arai-a** [franziskuskiefer/webcrypto-ec#3]
as far as I can see, EC private key is always paired with public key in WebCrypto level and also in NSS level, but current primitive APIs don't assume it.
specifically, `getPrivateKey` returns private key without corresponding public key, because generator is not given, and it can be different than `algorithm`'s one .

if private key is not representable alone in WebCrypto level, we should merge `getPrivateKey` and `mul`.
if not in NSS level, we should either merge them or modify NSS.

@franziskuskiefer , how do you think?

**Comment by franziskuskiefer** [comment]
Hm, not if I understand correctly. `getPrivateKey` gets the curve name. Thus the implementation behind it is able to compute the public key (the generator is fixed and known). So it shouldn't be a problem to add the public to the private key if we want to.

**Comment by arai-a** [comment]
I've chosen `CryptoKey` as the result and parameter types because the result of each operation has the same dimension as the public/private key.
`h mod n` is simply an integer, and private key (`x`) itself is also integer,
and also we're going to calculate `(h mod n) G'` that is a point on the `algorithm`'s curve, that is also the same operation as calculating public key from private key (`x G`),
so I thought it fits into the those type/strange.

but parameters are different here (at least `G'` is different than `G`), and there's no point of calculating `(h mod n) G` which won't be used.
do you think it's fine?

**Comment by franziskuskiefer** [comment]
Sure, we don't need the public key of `(h mod n) * G` right now but others might. If we define a general interface like this we shouldn't restrict it to the limited functionality we need right now. The operation is relatively cheap and I'd prefer having the interface do something we or others could re-use and fulfils expectations (having the public key in the private key) over saving one operation.

**Comment by arai-a** [comment]
Okay, I'll try implementing in that way.

then, in that case it would be better returning CryptoKeyPair object from getPrivateKey, instead of private CryptoKey only.

**Comment by arai-a** [comment]
changed
https://github.com/franziskuskiefer/webcrypto-ec/commit/f1c597ef333a29cec2275cf66f65a00c4a448bfd
