### ISSUE TITLE
Should we rename the interface SubtleCryptoEC ?

### ISSUE THREAD

**Issue by arai-a** [franziskuskiefer/webcrypto-ec#4]
other crypto methods are part of "SubtleCrypto" interfaces.

given that we'll implement this interface in `crypto.subtle`, using the similar name would make more sense.

**Comment by arai-a** [comment]
or maybe better adding a dedicated attribute to `crypto` which implements this interface?
like `crypto.subtleEC` or something?

**Comment by franziskuskiefer** [comment]
how about `crypto.subtle.ec`?

**Comment by arai-a** [comment]
yeah, sounds cleaner :)

how do you think about the interface name?

**Comment by franziskuskiefer** [comment]
I think we should use `crypto.subtle.ec` as interface name, making clear it's `subtle` (dangerous), and a "sub-interface" of webcrypto.

**Comment by arai-a** [comment]
sorry, I wasn't clear enough.
I was thinking about renaming the IDL interface name `WebCryptoEC` to `SubtleCryptoEC`, in order to make it match to existing `SubtleCrypto`.

this one:
https://franziskuskiefer.github.io/webcrypto-ec/doc.html#webcryptoec-interface
```
interface WebCryptoEC {
...
}
```

**Comment by arai-a** [comment]
for `ec` attribute on `crypto.subtle`, pushed https://github.com/franziskuskiefer/webcrypto-ec/commit/4a77fbd4f6c953ea4dcc9797d03d15787ddbd91f

**Comment by franziskuskiefer** [comment]
Ah sorry, I misunderstood. Yeah that rename to `SubtleCryptoEC` makes sense.

**Comment by arai-a** [comment]
thanks!
